xychart-beta
    title "Diagrama de Pareto - FieldOps | Principais Gargalos Operacionais"
    x-axis ["Peças", "Deslocamento", "Diagnóstico", "Offline", "Atraso", "Retrabalho", "GPS", "Outros"]
    y-axis "Ocorrências" 0 --> 350
    bar [300, 280, 230, 210, 190, 180, 140, 100]
    line [18.4, 35.6, 49.7, 62.6, 74.2, 85.2, 93.8, 100]

xychart-beta
    title "Pareto - Qualidade e Pós-Atendimento"
    x-axis ["Incompleto", "Atraso", "Limpeza", "Fatura/OS", "Retorno", "Outros"]
    y-axis "Ocorrências" 0 --> 310
    bar [290, 230, 180, 140, 100, 60]
    line [29, 52, 70, 84, 94, 100]

xychart-beta
    title "Pareto - Logística e Deslocamento"
    x-axis ["Trânsito", "Rota", "Redistribuição", "Veículo", "Acesso", "Outros"]
    y-axis "Ocorrências" 0 --> 340
    bar [320, 250, 170, 110, 90, 60]
    line [32, 57, 74, 85, 94, 100]

xychart-beta
    title "Pareto - Tecnologia e Aplicativo Mobile"
    x-axis ["Offline", "Fotos", "GPS", "Bateria", "Lentidão", "Outros"]
    y-axis "Ocorrências" 0 --> 300
    bar [280, 210, 190, 130, 110, 80]
    line [28, 49, 68, 81, 92, 100]