import { StyleSheet } from 'react-native';

export const auditPageStyles = StyleSheet.create({
  content: {
    padding: 14,
    paddingBottom: 40,
  },
  heading: { gap: 12 },
  headingText: { flex: 1 },
  eyebrow: {
    fontSize: 9,
    fontWeight: '900',
    color: '#2563eb',
    letterSpacing: 1.2,
  },
  title: {
    fontSize: 25,
    fontWeight: '900',
    marginTop: 5,
  },
  subtitle: {
    fontSize: 11,
    lineHeight: 17,
    marginTop: 5,
  },
  primaryButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#2563eb',
    height: 42,
    borderRadius: 9,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 14,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
  },
  auditBanner: { borderWidth: 1, borderRadius: 13, padding: 13, flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 18 },
  bannerIcon: { width: 38, height: 38, borderRadius: 10, backgroundColor: '#dbeafe', alignItems: 'center', justifyContent: 'center' },
  bannerText: { flex: 1 },
  bannerTitle: { fontSize: 12, fontWeight: '900' },
  bannerDescription: { fontSize: 10, lineHeight: 15, marginTop: 2 },
  eventCount: { color: '#2563eb', fontSize: 20, fontWeight: '900' },
  statsRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  statCard: { flex: 1, minHeight: 82, borderWidth: 1, borderRadius: 12, padding: 10 },
  statValue: { fontSize: 18, fontWeight: '900', marginTop: 6 },
  statLabel: { fontSize: 9, marginTop: 1 },
  searchBox: { height: 46, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 16 },
  searchInput: { flex: 1, fontSize: 12 },
  filterRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12 },
  filterButton: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 6 },
  filterButtonActive: { backgroundColor: '#eff6ff', borderColor: '#93c5fd' },
  filterText: { fontSize: 9, fontWeight: '800' },
  listHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginTop: 22, marginBottom: 9 },
  sectionTitle: { fontSize: 15, fontWeight: '900' },
  resultCount: { fontSize: 10 },
  timelineRow: { flexDirection: 'row', alignItems: 'stretch' },
  timelineRail: { width: 22, alignItems: 'center' },
  timelineDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#2563eb', marginTop: 18, zIndex: 1 },
  timelineLine: { width: 1, flex: 1, marginTop: -1 },
  eventCard: { flex: 1, borderWidth: 1, borderRadius: 13, padding: 13, marginBottom: 10 },
  eventHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 8 },
  eventTitleBlock: { flex: 1 },
  eventAction: { fontSize: 13, fontWeight: '900' },
  eventTime: { fontSize: 10, marginTop: 3 },
  eventType: { borderRadius: 999, backgroundColor: '#eff6ff', paddingHorizontal: 8, paddingVertical: 5 },
  eventTypeText: { color: '#1d4ed8', fontSize: 9, fontWeight: '900' },
  eventDescription: { fontSize: 10, lineHeight: 16, marginTop: 11 },
  resourceRow: { borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 11, paddingTop: 10 },
  resourceText: { flex: 1, fontSize: 10, fontWeight: '800' },
  eventFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 11 },
  actor: { flexDirection: 'row', alignItems: 'center', gap: 5, flex: 1 },
  actorText: { fontSize: 9 },
  eventId: { fontSize: 9 },
  emptyState: { borderWidth: 1, borderRadius: 13, padding: 28, alignItems: 'center', marginTop: 8 },
  emptyTitle: { fontSize: 14, fontWeight: '900', marginTop: 10 },
  emptyText: { fontSize: 11, marginTop: 5 },
  panel: {
    borderWidth: 1,
    borderRadius: 13,
    padding: 24,
    marginTop: 18,
    alignItems: 'center',
  },
  icon: {
    width: 62,
    height: 62,
    borderRadius: 15,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: '900',
    marginTop: 15,
  },
  body: {
    fontSize: 11,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 6,
    maxWidth: 430,
  },
});
