import { StyleSheet } from 'react-native';

export const equipmentPageStyles = StyleSheet.create({
  content: {
    padding: 14,
    paddingBottom: 40,
  },
  heading: { gap: 12 },
  headingText: { flex: 1 },
  eyebrow: {
    fontSize: 9,
    fontWeight: '900',
    color: '#2563eb',
    letterSpacing: 1.2,
  },
  title: {
    fontSize: 25,
    fontWeight: '900',
    marginTop: 5,
  },
  subtitle: {
    fontSize: 11,
    lineHeight: 17,
    marginTop: 5,
  },
  primaryButton: {
    alignSelf: 'flex-start',
    backgroundColor: '#2563eb',
    height: 42,
    borderRadius: 9,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginTop: 14,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
  },
  summaryRow: { flexDirection: 'row', gap: 8, marginTop: 18 },
  summaryCard: { flex: 1, minHeight: 70, borderWidth: 1, borderRadius: 12, padding: 10, justifyContent: 'center' },
  summaryValue: { fontSize: 20, fontWeight: '900' },
  summaryLabel: { fontSize: 9, marginTop: 2 },
  searchBox: { height: 46, borderWidth: 1, borderRadius: 10, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 16 },
  searchInput: { flex: 1, fontSize: 12 },
  filterRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 12 },
  filterButton: { borderWidth: 1, borderRadius: 999, paddingHorizontal: 9, paddingVertical: 6 },
  filterButtonActive: { backgroundColor: '#eff6ff', borderColor: '#93c5fd' },
  filterText: { fontSize: 9, fontWeight: '800' },
  listHeader: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginTop: 22, marginBottom: 9 },
  sectionTitle: { fontSize: 15, fontWeight: '900' },
  resultCount: { fontSize: 10 },
  equipmentCard: { borderWidth: 1, borderRadius: 13, padding: 14, marginBottom: 10 },
  cardTopRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  equipmentIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10 },
  equipmentIcon: { width: 40, height: 40, borderRadius: 10, backgroundColor: '#eff6ff', alignItems: 'center', justifyContent: 'center' },
  equipmentTitleBlock: { flex: 1 },
  equipmentName: { fontSize: 14, fontWeight: '900' },
  equipmentTag: { fontSize: 10, marginTop: 3 },
  moreButton: { padding: 3 },
  statusBadge: { alignSelf: 'flex-start', flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 999, paddingHorizontal: 8, paddingVertical: 5, marginTop: 12 },
  statusDot: { width: 6, height: 6, borderRadius: 3 },
  statusText: { fontSize: 9, fontWeight: '900' },
  locationRow: { borderTopWidth: 1, flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 13, paddingTop: 11 },
  locationText: { flex: 1, fontSize: 10 },
  infoRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginTop: 10 },
  infoItem: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  infoText: { fontSize: 9 },
  actionRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 13 },
  qrButton: { flexDirection: 'row', alignItems: 'center', gap: 5 },
  qrText: { color: '#2563eb', fontSize: 10, fontWeight: '900' },
  detailsButton: { paddingVertical: 4 },
  detailsText: { fontSize: 10, fontWeight: '800' },
  emptyState: { borderWidth: 1, borderRadius: 13, padding: 28, alignItems: 'center', marginTop: 8 },
  emptyTitle: { fontSize: 14, fontWeight: '900', marginTop: 10 },
  emptyText: { fontSize: 11, marginTop: 5 },
  panel: {
    borderWidth: 1,
    borderRadius: 13,
    padding: 24,
    marginTop: 18,
    alignItems: 'center',
  },
  icon: {
    width: 62,
    height: 62,
    borderRadius: 15,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: '900',
    marginTop: 15,
  },
  body: {
    fontSize: 11,
    lineHeight: 18,
    textAlign: 'center',
    marginTop: 6,
    maxWidth: 430,
  },
});
