import { StyleSheet } from 'react-native';

export const inspectionsPageStyles = StyleSheet.create({
  content: { padding: 14, paddingBottom: 40 },
  heading: { flexDirection: 'row', gap: 10, alignItems: 'flex-start' },
  headingText: { flex: 1 },
  eyebrow: { fontSize: 9, fontWeight: '900', color: '#2563eb', letterSpacing: 1.2, marginTop: 4 },
  title: { fontSize: 24, fontWeight: '900', marginTop: 4 },
  subtitle: { fontSize: 11, lineHeight: 17, marginTop: 5 },
  newButton: { backgroundColor: '#2563eb', height: 40, borderRadius: 9, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 5 },
  buttonText: { color: '#ffffff', fontSize: 11, fontWeight: '900' },
  back: { color: '#2563eb', fontSize: 12, fontWeight: '800', marginBottom: 16 },
  statusWrapper: { marginTop: 10 },
  panel: { borderWidth: 1, borderRadius: 12, padding: 15, marginTop: 14 },
  panelTitle: { fontSize: 14, fontWeight: '900' },
  panelTitleSpaced: { fontSize: 14, fontWeight: '900', marginTop: 20 },
  banner: { flexDirection: 'row', gap: 12, alignItems: 'center' },
  bannerText: { flex: 1 },
  qr: { width: 62, height: 62, borderWidth: 1, borderRadius: 9, alignItems: 'center', justifyContent: 'center', backgroundColor: '#ffffff' },
  small: { fontSize: 9, lineHeight: 14, marginTop: 3 },
  progressLabel: { fontSize: 9, marginTop: 8 },
  progressTrack: { height: 5, backgroundColor: '#e2e8f0', borderRadius: 5, marginTop: 4 },
  progressFill: { height: '100%', backgroundColor: '#2563eb', borderRadius: 5 },
  checklistRow: { flexDirection: 'row', alignItems: 'center', gap: 9, paddingVertical: 13, borderBottomWidth: 1 },
  checklistText: { flex: 1 },
  checklistTitle: { fontSize: 11, fontWeight: '800' },
  answer: { fontSize: 8, color: '#15803d', backgroundColor: '#dcfce7', paddingHorizontal: 6, paddingVertical: 4, borderRadius: 5, fontWeight: '900' },
  evidence: { height: 130, borderWidth: 1, borderStyle: 'dashed', borderRadius: 10, alignItems: 'center', justifyContent: 'center', marginTop: 10, gap: 5 },
  info: { paddingVertical: 11, borderBottomWidth: 1, flexDirection: 'row', justifyContent: 'space-between', gap: 10 },
  infoValue: { fontSize: 10, fontWeight: '800', flex: 1, textAlign: 'right' },
  approve: { height: 44, borderRadius: 9, backgroundColor: '#2563eb', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7, marginTop: 14 },
  reject: { height: 44, borderRadius: 9, borderWidth: 1, borderColor: '#fecaca', alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 7, marginTop: 8 },
  rejectText: { color: '#dc2626', fontSize: 11, fontWeight: '900' },
  empty: { textAlign: 'center', paddingVertical: 50, fontSize: 12 },
});
