import { StyleSheet } from 'react-native';

export const settingsPageStyles = StyleSheet.create({
  content: {
    padding: 14,
    paddingBottom: 40,
  },
  eyebrow: {
    fontSize: 9,
    fontWeight: '900',
    color: '#2563eb',
    letterSpacing: 1.2,
  },
  title: {
    fontSize: 25,
    fontWeight: '900',
    marginTop: 5,
  },
  subtitle: {
    fontSize: 11,
    lineHeight: 17,
    marginTop: 5,
  },
  profileCard: {
    borderWidth: 1,
    borderRadius: 13,
    padding: 14,
    marginTop: 18,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 11,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#dbeafe',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: '#1d4ed8',
    fontSize: 13,
    fontWeight: '900',
  },
  profileInfo: { flex: 1 },
  profileName: { fontSize: 14, fontWeight: '900' },
  profileRole: { fontSize: 10, marginTop: 3 },
  profileEmail: { fontSize: 10, marginTop: 2 },
  chevronButton: { padding: 4 },
  sectionTitle: { fontSize: 14, fontWeight: '900', marginTop: 22, marginBottom: 9 },
  settingsCard: { borderWidth: 1, borderRadius: 13, paddingHorizontal: 13 },
  settingRow: { minHeight: 66, flexDirection: 'row', alignItems: 'center', gap: 10 },
  settingIcon: { width: 34, height: 34, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  settingCopy: { flex: 1 },
  settingTitle: { fontSize: 12, fontWeight: '800' },
  settingDescription: { fontSize: 10, lineHeight: 15, marginTop: 2 },
  divider: { height: 1 },
  toggle: { width: 40, height: 23, borderRadius: 12, padding: 3, backgroundColor: '#cbd5e1', justifyContent: 'center' },
  toggleActive: { backgroundColor: '#2563eb' },
  toggleThumb: { width: 17, height: 17, borderRadius: 9, backgroundColor: '#ffffff' },
  toggleThumbActive: { alignSelf: 'flex-end' },
  securityCard: { minHeight: 66, borderWidth: 1, borderRadius: 13, paddingHorizontal: 13, flexDirection: 'row', alignItems: 'center', gap: 10 },
  securityIcon: { width: 34, height: 34, borderRadius: 9, backgroundColor: '#dcfce7', alignItems: 'center', justifyContent: 'center' },
  version: { fontSize: 10, textAlign: 'center', marginTop: 25 },
});
